[build]
  publish = "article-platform/frontend"

# Firebase config values are public client-side configuration
# Security is handled by Firebase Security Rules, not by hiding these values
[build.environment]
  # Tell Netlify these are not secrets
  REVIEW_SKIP_SECRET_DETECTION = "true"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
